[package]
name = "rsfindhash"
version = "0.1.0"
authors = ["Jack Bowman <jack@umich.edu>"]
edition = "2018"

[dependencies]
md5 = "0.7.0"
rand = "0.7.3"
ctrlc = "3.1.3"
termion = "1.5.5"
num_cpus = "1.12.0"